### ISSUE TITLE
yarn dev or npm run dev doesn't do anything

### ISSUE THREAD

**Issue by alexanderbkl** [dwisulfahnur/solana-blog#1]
localhost:3000 is blank and no connection to it.

**Comment by alexanderbkl** [comment]
Running yarn build prompts this error:


> Build error occurred
TypeError: Cannot read properties of undefined (reading '_bn')
    at isPublicKeyData (/home/alex/smartcontract/solana-blog/app/node_modules/@solana/web3.js/lib/index.cjs.js:1835:16)
    at new PublicKey (/home/alex/smartcontract/solana-blog/app/node_modules/@solana/web3.js/lib/index.cjs.js:1853:9)
    at translateAddress (/home/alex/smartcontract/solana-blog/app/node_modules/@project-serum/anchor/dist/cjs/program/common.js:47:63)
    at AccountClient.getAccountInfo (/home/alex/smartcontract/solana-blog/app/node_modules/@project-serum/anchor/dist/cjs/program/namespace/account.js:230:96)
    at AccountClient.fetchNullable (/home/alex/smartcontract/solana-blog/app/node_modules/@project-serum/anchor/dist/cjs/program/namespace/account.js:88:40)
    at AccountClient.fetch (/home/alex/smartcontract/solana-blog/app/node_modules/@project-serum/anchor/dist/cjs/program/namespace/account.js:100:33)
    at getAllPosts (/home/alex/smartcontract/solana-blog/app/.next/server/chunks/569.js:47:50)
    at getStaticPaths (/home/alex/smartcontract/solana-blog/app/.next/server/pages/posts/[pid].js:177:91)
    at buildStaticPaths (/home/alex/smartcontract/solana-blog/app/node_modules/next/dist/build/utils.js:491:37)
    at /home/alex/smartcontract/solana-blog/app/node_modules/next/dist/build/utils.js:632:125 {
  type: 'TypeError'
}
